@startuml
|管理者|
  start
  :自動販売機の施錠を解除しドアを開ける;

|システム|
  :売上ボックスへのアクセスを許可;
  :現在の売上金額・回収履歴を表示;
  ->管理者: 現在の売上金額・回収案内を通知;

|管理者|
  :売上金額・回収案内を確認;
  :売上金ボックスから売上金を回収;

  if (回収中にエラー発生?) then (Yes)
    |システム|
      :回収口の故障や異常（詰まり等）を表示;
      ->管理者: エラー通知;
    |管理者|
      :エラー通知を確認し、回収を中断または他手段を検討;
      stop
  else (No)
    :回収完了を目視・数値で確認;
    if (釣銭補充) then (Yes)
    :釣銭を補充、または点検;
    else (No)
    endif

    |システム|
      :回収金額や担当者入力・登録を促す;
      ->管理者: 回収登録案内を通知;
    |管理者|
      :回収金額・担当者などを入力・登録;
    |システム|
      :回収日時・金額・担当者などの履歴を記録;
      if (回収履歴の記録ができなかった場合) then (yes)
        |管理者|
        :紙で記録する;
        stop
      endif
    |管理者|
      :売上ボックスを閉じドアを施錠;

      stop
  endif
@enduml