@startuml
|利用者|
  start
  :商品購入またはキャンセル後、返金・釣銭受け取り操作を待つ;

|システム|
  :取引終了時に釣銭や返金が必要か判断;
  if (釣銭や返金あり?) then (Yes)
    :釣銭/返金金額を算出;
    :釣銭・返金排出口に金額を払い出す;
    :釣銭・返金の払い出しを案内;
    ->利用者: 釣銭・返金払い出し通知;
  else (No)
    :通知なし;
  endif

|利用者|
  if (払い出し通知あり?) then (Yes)
    :釣銭・返金を排出口から受け取る;
  endif

stop
@enduml