@startuml
actor 利用者
activate 利用者
collections 自動販売機

表示パネル -> 商品ラック : 商品の在庫_情報を取得()
activate 表示パネル
activate 商品ラック

表示パネル -> 釣銭機 : 現在の釣銭残量を取得する()
activate 釣銭機

表示パネル <- 表示パネル: 商品一覧_商品名_商品価格_商品在庫有無等_を表示()
表示パネル -> 利用者 : 商品一覧_商品名_商品価格_商品在庫有無

表示パネル <- 表示パネル: 釣銭有無を表示()
表示パネル -> 利用者 : 釣銭有無
hnote over 自動販売機 : 待機中


利用者 -> 投入金口: お金投入
activate 投入金口

hnote over 自動販売機 : 入金受付中

投入金口 -> 投入金口 : 投入された金額を確認()
投入金口 -> 投入金口 : 金額認識()
投入金口 -> 投入金口 : 投入金額を取得()
投入金口 -> 投入金口 : 合計投入金額を更新()
投入金口 -> 表示パネル: 合計投入金額を表示()
利用者 <- 表示パネル: 合計投入金額

opt [投入金額>=商品価格 and 釣銭あり]

    投入金口 -> 操作パネル : 商品選択待ち
    activate 操作パネル
    hnote over 自動販売機 : 商品選択待ち
    操作パネル -> 操作パネル: 選択可能な商品ボタンを点灯()
    操作パネル -> 利用者 : 選択可能な商品ボタン

    利用者 -> 操作パネル: 商品ボタン押下
    操作パネル -> 商品ラック: 商品を払い出す()
    hnote over 自動販売機 : 商品払い出し
    deactivate 操作パネル

    商品ラック -> 商品取り出し口: 商品を受け取る()
    deactivate 商品ラック
    activate 商品取り出し口

    商品取り出し口 -> 利用者: 商品
    deactivate 商品取り出し口

    投入金口 -> 釣銭機: 釣銭の確認
    hnote over 自動販売機 : 釣銭_返金処理中
    deactivate 投入金口

    opt [お釣りあり]
        釣銭機 -> 釣銭機 : 現在の釣銭残量を取得する()
        釣銭機 -> 表示パネル: 釣銭・返金の払い出しを案内()
        表示パネル -> 利用者: 釣銭・返金の有無
        deactivate 表示パネル
        釣銭機 -> 釣銭機: 釣銭_返金排出口に金額を払い出す()
        釣銭機 -> 利用者 : 釣銭
        deactivate 釣銭機
        deactivate 利用者
    end
end
deactivate 利用者

@enduml