@startuml
' 自動販売機のハードウェア構成をコンポジット集約で表現

left to right direction

class 自動販売機 {
}

class 表示パネル {
    -商品名: List
    -商品価格: List
    -商品在庫有無: List
    -釣銭有無: bool
    +商品一覧_商品名_商品価格_商品在庫有無等_を表示()

    +釣銭有無を表示()

    +釣銭_返金の払い出しを案内()
    +通知なし()
    +合計投入金額を表示()
}

class 商品ラック {
    -商品: List
    -商品在庫: List
    +商品の在庫_情報を取得()

    +商品を払い出す()
}

class 投入金口 {
    -投入金額 : int
    +合計投入金額 : int
    +待機状態になる()
    +投入された金額を確認()
    +金額認識()
    +投入金額を取得()
    +合計投入金額を更新()
    +投入物を返却()
}

class 釣銭機 {
    -釣銭 : int
    +現在の釣銭残量を取得する()

    +釣銭_返金排出口に金額を払い出す()
}

class 商品取り出し口 {
    +商品を受け取る()
}

class 売上金庫 {
    +売上金を保管する()
    +売上金を回収する()
}

class 操作パネル {
    +商品ボタン : List
    +選択商品 : 
    +選択可能な商品ボタンを点灯()

    +商品ボタン押下を確認()
    +投入金額_商品在庫および釣銭状況を確認()
    +購入処理完了()
}

自動販売機 *-- 表示パネル
自動販売機 *-- 商品ラック
自動販売機 *-- 投入金口
自動販売機 *-- 釣銭機
自動販売機 *-- 商品取り出し口
自動販売機 *-- 売上金庫
自動販売機 *-- 操作パネル

@enduml