@startuml

left to right direction

actor 利用者
actor 管理者
actor メンテナンス担当者

rectangle 自動販売機 {
    usecase 商品一覧を表示する as UC1
    usecase 商品を選択し購入する as UC2
    usecase お金を投入する as UC3
    usecase 釣銭_返金を受け取る as UC4
    usecase 売上金を回収する  as UC5
    usecase 商品を補充する as UC6
    usecase 釣銭を補充する as UC7
    usecase 販売商品を変更する as UC8
    usecase 故障対応を行う as UC9
    usecase 機械の状態を確認する as UC10
}

利用者 -- UC1
利用者 -- UC2
利用者 -- UC3
管理者 -- UC8
利用者 -- UC4
管理者 -- UC5
管理者 -- UC6
管理者 -- UC7

メンテナンス担当者 -- UC9
管理者 -- UC10

@enduml