
@startuml

state 管理モード {
    [*] --> 売上金回収
    売上金回収 : do/売上金を回収する
    売上金回収 --> 商品補充 : 商品補充選択
    商品補充 : do/商品を補充する
    商品補充 --> 釣銭補充 : 釣銭補充選択
    釣銭補充 : do/釣銭を補充する
    釣銭補充 --> 販売商品変更 : 販売商品変更選択
    販売商品変更 : do/販売商品を変更する
    販売商品変更 --> 機械状態確認 : 機械状態確認選択
    機械状態確認 : do/機械の状態を確認する
    機械状態確認 --> [*] : 管理モード終了選択
}

@enduml