
@startuml

state 故障中 {
    state c3 <<choice>>
    [*] --> c3
    停止理由表示 : do/停止理由を表示する
    c3 --> 停止理由表示: [お金投入なし]
    投入金返却 : exit/投入金または釣銭を返金する
    c3 --> 投入金返却 : [お金投入あり]
    投入金返却 --> 停止理由表示
}

@enduml