@startuml
[*] --> 販売中

state 販売中 {
    販売中 : do/商品一覧を表示する

    [*] --> お金投入待ち
    お金投入待ち --> 入金受付中 : お金投入
    入金受付中 --> 入金受付中 : お金投入
    入金受付中 --> 商品選択待ち : [投入金額>=価格]
    入金受付中 --> 釣銭_返金処理中 : キャンセル


    商品選択待ち --> 購入処理中 : 商品選択
    商品選択待ち --> 釣銭_返金処理中 : キャンセル
    購入処理中 --> 商品払い出し : 購入処理完了

    state c2 <<choice>>
    商品払い出し --> c2
    c2 --> 釣銭_返金処理中 : [お釣りあり]
    c2 --> お金投入待ち : [お釣りなし]

    釣銭_返金処理中 --> お金投入待ち : 釣銭・返金受取
}

販売中 --> 販売停止中 : 故障検知/販売停止指示
販売停止中 --> 販売中 : 復旧/販売再開指示

state 販売停止中 {
    state c <<choice>>
    [*] --> c
    c --> 停止理由表示: [お金投入なし]
    c --> 投入金返却 : [お金投入あり]
    投入金返却 --> 停止理由表示
}

@enduml