@startuml
[*] --> 販売中 : 電源ON/初期化する

state 販売中 {
    販売中 : do/お金投入を監視する,品在庫を確認する,釣銭を確認する,商品一覧を表示する,釣銭有無を表示する

    [*] --> 待機中
    待機中 --> 入金受付中 : お金投入

    入金受付中 : do/合計投入金額を表示する
    入金受付中 --> 入金受付中 : お金投入
    商品選択待ち --> 入金受付中 : お金投入
    入金受付中 --> 商品選択待ち : [投入金額>=価格 and 釣銭あり]
    入金受付中 --> 釣銭_返金処理中 : 購入キャンセル

    商品選択待ち : entry/購入可能な商品ボタンを選択可能にする
    商品選択待ち : do/商品ボタン押下を監視する
    商品選択待ち --> 商品払い出し : 購入処理完了
    商品選択待ち --> 釣銭_返金処理中 : 購入キャンセル

    商品払い出し : exit/購入商品を払いだす

    state c2 <<choice>>
    商品払い出し --> c2
    c2 --> 釣銭_返金処理中 : [お釣りあり]
    c2 --> 待機中 : [お釣りなし]
    釣銭_返金処理中 : exit/投入金または釣銭を返金する

    釣銭_返金処理中 --> 待機中 : 釣銭・返金受取

}

販売中 --> 販売停止中 : メンテナンス操作,管理者操作,故障検知/販売を停止する
販売停止中 --> 販売中 : メンテナンスモード終了,管理モード終了/販売を再開する

state 販売停止中 {
    state c <<choice>>
    [*] --> c
    c --> 故障中 : [故障]
    c --> 管理モード : [管理モード]
    c --> メンテナンスモード : [メンテナンスモード]
}

故障中 --> メンテナンスモード : メンテナンス選択

販売中 --> [*] : 電源OFF/シャットダウンする
販売停止中 --> [*] : 電源OFF/シャットダウンする

@enduml