@startuml
actor 利用者
hnote over 自動販売機: 待機中
自動販売機 -> 商品ラック : 商品の在庫_情報を取得
自動販売機 -> 釣銭機 : 現在の釣銭残量を取得する
自動販売機 -> 表示パネル : 商品一覧_商品名_商品価格_商品在庫有無等_を表示(商品在庫情報)
表示パネル -> 利用者 : 商品、価格、在庫有無
自動販売機 -> 表示パネル : 釣銭有無を表示(釣銭残量)
表示パネル -> 利用者 : 釣銭有無
hnote over 自動販売機: お金投入
利用者 -> 投入金口 : お金投入
自動販売機 -> 投入金口 : 投入された金額を確認
投入金口 -> 投入金口 : 金額認識
投入金口 -> 投入金口 : 投入金額を取得
投入金口 -> 投入金口 : 合計投入金額を更新
自動販売機 -> 表示パネル : 合計投入金額を表示(投入金額)
表示パネル -> 利用者 : 合計投入金額
自動販売機 -> 操作パネル : 選択可能な商品ボタンを点灯
操作パネル -> 利用者 : 選択可能な商品ボタン
hnote over 自動販売機: 商品選択中
利用者 -> 操作パネル : 商品ボタン押下
自動販売機 -> 操作パネル : 商品ボタン押下を確認
自動販売機 -> 商品ラック : 商品を払い出す
自動販売機 -> 商品取り出し口 : 商品を受け取る
商品取り出し口 -> 利用者 : 商品
自動販売機 -> 釣銭機 : 現在の釣銭残量を取得する
hnote over 自動販売機: 釣銭払い出し
自動販売機 -> 表示パネル : 釣銭_返金の払い出しを案内
表示パネル -> 利用者 : 釣銭_返金の有無
自動販売機 -> 釣銭機 : 釣銭_返金排出口に金額を払い出す
釣銭機 -> 利用者 : 釣銭
hnote over 自動販売機: 購入完了

@enduml