@startuml
|利用者|
  start
  :自動販売機の前に立つ;
  
|システム|
  :待機状態になる;

|利用者|
  :お金を投入する;

|システム|
  :投入金額を表示;
  :選択可能な商品ボタンを点灯;
  ->利用者: 投入金額・選択可能商品を通知;

|利用者|
  :投入金額・選択可能商品を確認する;
  :購入したい商品ボタンを押す;

|システム|
  :商品在庫および釣銭状況を確認;
  if (在庫・釣銭OK?) then (Yes)
    :商品を払い出す;
    :必要に応じてお釣りを払い出す;
    :商品/お釣りの払い出しを通知;
    ->利用者: 商品_お釣りの払い出しを通知;
  else (No)
    :エラー内容（在庫切れや釣銭切れ等）を表示;
    ->利用者: エラー内容を通知;
  endif

|利用者|
  if (商品・お釣りの払い出し通知) then (Yes)
    :商品・お釣りを受け取る;
  else (エラー通知)
    :エラー内容を確認し、再選択や投入金返却を検討する;
  endif
  end

@enduml